spring.application.name=safezone-backend

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,modulith
